# Generated by Django 4.1.6 on 2023-03-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_account_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, default='static/images/avatar/default_img.jpg', upload_to='static/images/avatar/'),
        ),
    ]
