# Generated by Django 4.1.6 on 2023-03-21 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 21, 0, 4, 35, 3063, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
