# Generated by Django 4.1.6 on 2023-05-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_account_photo_alter_comment_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, default='static/images/avatar/default/default_img.jpg', upload_to='static/images/avatar/', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
