# Generated by Django 4.2.4 on 2023-08-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_post_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
