# Generated by Django 4.2.4 on 2023-08-10 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_comment_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='update_time',
        ),
    ]
