# Generated by Django 4.2.5 on 2023-09-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(default='static/images/avatar/default/default_img.jpg', upload_to='static/images/avatar/', verbose_name='Фото профиля'),
        ),
    ]
