# Generated by Django 4.2.5 on 2023-09-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_account_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/images/avatar/', verbose_name='Фото профиля'),
        ),
    ]
