# Generated by Django 4.2.5 on 2023-09-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_account_birthday_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.DateField(default=None, null=True),
        ),
    ]
