# Generated by Django 4.2.5 on 2023-09-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_account_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, default='static/images/avatar/default/default_img.jpg', upload_to='static/images/avatar/', verbose_name='Фото профиля'),
        ),
    ]
